//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmy()
        {
            this.Seanse = new HashSet<Seanse>();
        }
    
        public int IdFilmu { get; set; }
        public string Tytuł { get; set; }
        public string Opis { get; set; }
        public Nullable<int> IdGatunku { get; set; }
        public string Rezyser { get; set; }
        public Nullable<int> RokProdukcji { get; set; }
        public Nullable<decimal> CzasTrwania { get; set; }
        public Nullable<int> LimitWiekowy { get; set; }
    
        public virtual Gatunki Gatunki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seanse> Seanse { get; set; }
    }
}
