//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seanse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seanse()
        {
            this.Zamowienia = new HashSet<Zamowienia>();
        }
    
        public int IdSeansu { get; set; }
        public Nullable<int> IdSali { get; set; }
        public Nullable<int> IdFilmu { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.TimeSpan> Godzina { get; set; }
        public Nullable<int> IdTypuSeansu { get; set; }
    
        public virtual Filmy Filmy { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual TypySeansow TypySeansow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia> Zamowienia { get; set; }
    }
}
