//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypySeansow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypySeansow()
        {
            this.Seanse = new HashSet<Seanse>();
        }
    
        public int IdTypuSeansu { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public Nullable<bool> WymaganeOkulary3D { get; set; }
        public bool CzyAktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seanse> Seanse { get; set; }
    }
}
