//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia
    {
        public int IdZamowienia { get; set; }
        public Nullable<int> IdSeansu { get; set; }
        public Nullable<int> IdKlienta { get; set; }
        public Nullable<int> IdTypuBiletu { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Seanse Seanse { get; set; }
        public virtual TypyBiletow TypyBiletow { get; set; }
    }
}
