//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adresy()
        {
            this.Kontrahencis = new HashSet<Kontrahenci>();
        }
    
        public int IdAdresu { get; set; }
        public string NrDomu { get; set; }
        public string NrLokalu { get; set; }
        public string Ulica { get; set; }
        public string KodPocztowy { get; set; }
        public string Poczta { get; set; }
        public string Powiat { get; set; }
        public string Miasto { get; set; }
        public string Wojewodztwo { get; set; }
        public string Kraj { get; set; }
        public string Gmina { get; set; }
        public string NrTelefonu { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrahenci> Kontrahencis { get; set; }
    }
}
