//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FakturyEntities : DbContext
    {
        public FakturyEntities()
            : base("name=FakturyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresy> Adresies { get; set; }
        public virtual DbSet<Faktury> Fakturies { get; set; }
        public virtual DbSet<Kontrahenci> Kontrahencis { get; set; }
        public virtual DbSet<PozycjeFaktury> PozycjeFakturies { get; set; }
        public virtual DbSet<Rodzaje> Rodzajes { get; set; }
        public virtual DbSet<SposobyPlatnosci> SposobyPlatnoscis { get; set; }
        public virtual DbSet<Statusy> Statusies { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Towary> Towaries { get; set; }
    }
}
